### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by noodlemctwoodle** [mikefitz888/Azure-Manic-7Pace#10]
Created packaged installer in the interest of security, running unsigned scripts in Powershell requires the user to disable script signing. If script signing is not turned back on after code has been executed it leaves the door wide open to an attacker to run arbitrary code on the users machine. 

Created new [Pull Request](https://github.com/mikefitz888/Azure-Manic-7Pace/pull/11)

**Comment by mikefitz888** [comment]
Merged.
