### ISSUE TITLE
When is the packaged installer coming?

### ISSUE THREAD

**Issue by noodlemctwoodle** [mikefitz888/Azure-Manic-7Pace#4]
A packaged installer would make it easier to install and minimise installation and configuration issues.

**Comment by mikefitz888** [comment]
I feel this is overkill at the moment. Feel free to add one if you like.

**Comment by mikefitz888** [comment]
The current PR #6 adds a PowerShell script for quickly installing/updating the plugin.

**Comment by mikefitz888** [comment]
Closing issue as PowerShell install script has been merged.

**Comment by noodlemctwoodle** [comment]
Created packaged installer in the interest of security and running unsigned scripts in Powershell
