### ISSUE TITLE
Comments include "via:azureWorkItemPlugin"

### ISSUE THREAD

**Issue by noodlemctwoodle** [mikefitz888/Azure-Manic-7Pace#5]
When adding comments to your work Items from Manic Time they apppear in Azure DevOps wrapped with the follwoing text ``via:azureWorkItemPlugin[00]``. The number in the ``[ ]`` appears to change, however I'm note sure what it represents? 

Is it possible to remove all the the text ``via:azureWorkItemPlugin[00]`` that your custom comment follows?

**Comment by mikefitz888** [comment]
The number represents the tag activity Id within ManicTime. This line is used to indicate the source of the log entry, as well as for making the upload process idempotent.

**Comment by mikefitz888** [comment]
I cannot remove it until there is a better way to achieve this. I will close this issue until then.
